// Copyright 2018 Google LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package syscalls

import (
	"golang.org/x/sys/unix"
)

const archWidth = 64

// This is the amd64 syscall map. One might think that this one map could be used for all Linux
// flavors on all architectures. Ah, no. It's Linux, not Plan 9. Every arch has a different
// system call set.
var syscalls = SyscallMap{
	unix.SYS_READ:                   makeSyscallInfo("read", Hex, FD, ReadBuffer, Hex),
	unix.SYS_WRITE:                  makeSyscallInfo("write", Hex, FD, WriteBuffer, Hex),
	unix.SYS_OPEN:                   makeSyscallInfo("open", Hex, Path, OpenFlags, Mode),
	unix.SYS_CLOSE:                  makeSyscallInfo("close", Hex, FD),
	unix.SYS_STAT:                   makeSyscallInfo("stat", Hex, Path, Stat),
	unix.SYS_FSTAT:                  makeSyscallInfo("fstat", Hex, FD, Stat),
	unix.SYS_LSTAT:                  makeSyscallInfo("lstat", Hex, Path, Stat),
	unix.SYS_POLL:                   makeSyscallInfo("poll", Hex, Hex, Hex, Hex),
	unix.SYS_LSEEK:                  makeSyscallInfo("lseek", Hex, FD, Hex, Hex),
	unix.SYS_MMAP:                   makeSyscallInfo("mmap", Hex, Hex, Hex, MMapProt, MMapFlags, FD, Hex),
	unix.SYS_MPROTECT:               makeSyscallInfo("mprotect", Hex, Hex, Hex, Hex),
	unix.SYS_MUNMAP:                 makeSyscallInfo("munmap", Hex, Hex, Hex),
	unix.SYS_BRK:                    makeSyscallInfo("brk", Hex, Hex),
	unix.SYS_RT_SIGACTION:           makeSyscallInfo("rt_sigaction", Hex, Signal, Hex, Hex),
	unix.SYS_RT_SIGPROCMASK:         makeSyscallInfo("rt_sigprocmask", Hex, Hex, Hex, Hex, Hex),
	unix.SYS_RT_SIGRETURN:           makeSyscallInfo("rt_sigreturn", Hex),
	unix.SYS_IOCTL:                  makeSyscallInfo("ioctl", Hex, FD, Hex, Hex),
	unix.SYS_PREAD64:                makeSyscallInfo("pread64", Hex, FD, ReadBuffer, Hex, Hex),
	unix.SYS_PWRITE64:               makeSyscallInfo("pwrite64", Hex, FD, WriteBuffer, Hex, Hex),
	unix.SYS_READV:                  makeSyscallInfo("readv", Hex, FD, ReadIOVec, Hex),
	unix.SYS_WRITEV:                 makeSyscallInfo("writev", Hex, FD, WriteIOVec, Hex),
	unix.SYS_ACCESS:                 makeSyscallInfo("access", Hex, Path, Oct),
	unix.SYS_PIPE:                   makeSyscallInfo("pipe", Hex, PipeFDs),
	unix.SYS_SELECT:                 makeSyscallInfo("select", Hex, FD, Hex, Hex, Hex, Timeval),
	unix.SYS_SCHED_YIELD:            makeSyscallInfo("sched_yield", Hex),
	unix.SYS_MREMAP:                 makeSyscallInfo("mremap", Hex, Hex, Hex, Hex, Hex, Hex),
	unix.SYS_MSYNC:                  makeSyscallInfo("msync", Hex, Hex, Hex, Hex),
	unix.SYS_MINCORE:                makeSyscallInfo("mincore", Hex, Hex, Hex, Hex),
	unix.SYS_MADVISE:                makeSyscallInfo("madvise", Hex, Hex, Hex, MADVFlags),
	unix.SYS_SHMGET:                 makeSyscallInfo("shmget", Hex, Hex, Hex, Hex),
	unix.SYS_SHMAT:                  makeSyscallInfo("shmat", Hex, Hex, Hex, Hex),
	unix.SYS_SHMCTL:                 makeSyscallInfo("shmctl", Hex, Hex, Hex, Hex),
	unix.SYS_DUP:                    makeSyscallInfo("dup", Hex, FD),
	unix.SYS_DUP2:                   makeSyscallInfo("dup2", Hex, FD, FD),
	unix.SYS_DUP3:                   makeSyscallInfo("dup3", Hex, FD, FD, SockFlags),
	unix.SYS_PAUSE:                  makeSyscallInfo("pause", Hex),
	unix.SYS_NANOSLEEP:              makeSyscallInfo("nanosleep", Hex, Timespec, PostTimespec),
	unix.SYS_GETITIMER:              makeSyscallInfo("getitimer", Hex, ItimerType, PostItimerVal),
	unix.SYS_ALARM:                  makeSyscallInfo("alarm", Hex, Hex),
	unix.SYS_SETITIMER:              makeSyscallInfo("setitimer", Hex, ItimerType, ItimerVal, PostItimerVal),
	unix.SYS_GETPID:                 makeSyscallInfo("getpid", PID),
	unix.SYS_SENDFILE:               makeSyscallInfo("sendfile", Hex, FD, FD, Hex, Hex),
	unix.SYS_SOCKET:                 makeSyscallInfo("socket", FD, SockFamily, SockType, SockProtocol),
	unix.SYS_CONNECT:                makeSyscallInfo("connect", Hex, FD, SockAddr, Hex),
	unix.SYS_ACCEPT:                 makeSyscallInfo("accept", Hex, FD, PostSockAddr, SockLen),
	unix.SYS_SENDTO:                 makeSyscallInfo("sendto", Hex, FD, Hex, Hex, Hex, SockAddr, Hex),
	unix.SYS_RECVFROM:               makeSyscallInfo("recvfrom", Hex, FD, Hex, Hex, Hex, PostSockAddr, SockLen),
	unix.SYS_SENDMSG:                makeSyscallInfo("sendmsg", Hex, FD, SendMsgHdr, Hex),
	unix.SYS_RECVMSG:                makeSyscallInfo("recvmsg", Hex, FD, RecvMsgHdr, Hex),
	unix.SYS_SHUTDOWN:               makeSyscallInfo("shutdown", Hex, FD, Hex),
	unix.SYS_BIND:                   makeSyscallInfo("bind", Hex, Hex, SockAddr, Hex),
	unix.SYS_LISTEN:                 makeSyscallInfo("listen", Hex, Hex, Hex),
	unix.SYS_GETSOCKNAME:            makeSyscallInfo("getsockname", Hex, Hex, PostSockAddr, SockLen),
	unix.SYS_GETPEERNAME:            makeSyscallInfo("getpeername", Hex, Hex, PostSockAddr, SockLen),
	unix.SYS_SOCKETPAIR:             makeSyscallInfo("socketpair", Hex, SockFamily, SockType, SockProtocol, Hex),
	unix.SYS_SETSOCKOPT:             makeSyscallInfo("setsockopt", Hex, Hex, Hex, Hex, Hex, Hex),
	unix.SYS_GETSOCKOPT:             makeSyscallInfo("getsockopt", Hex, Hex, Hex, Hex, Hex, Hex),
	unix.SYS_CLONE:                  makeSyscallInfo("clone", Hex, CloneFlags, Hex, Hex, Hex, Hex),
	unix.SYS_FORK:                   makeSyscallInfo("fork", Hex),
	unix.SYS_VFORK:                  makeSyscallInfo("vfork", Hex),
	unix.SYS_EXECVE:                 makeSyscallInfo("execve", Hex, Path, ExecveStringVector, ExecveStringVector),
	unix.SYS_EXIT:                   makeSyscallInfo("exit", Hex, Hex),
	unix.SYS_WAIT4:                  makeSyscallInfo("wait4", Hex, Hex, Hex, Hex, Rusage),
	unix.SYS_KILL:                   makeSyscallInfo("kill", Hex, PID, Signal),
	unix.SYS_UNAME:                  makeSyscallInfo("uname", Hex, Uname),
	unix.SYS_SEMGET:                 makeSyscallInfo("semget", Hex, Hex, Hex, Hex),
	unix.SYS_SEMOP:                  makeSyscallInfo("semop", Hex, Hex, Hex, Hex),
	unix.SYS_SEMCTL:                 makeSyscallInfo("semctl", Hex, Hex, Hex, Hex, Hex),
	unix.SYS_SHMDT:                  makeSyscallInfo("shmdt", Hex, Hex),
	unix.SYS_MSGGET:                 makeSyscallInfo("msgget", Hex, Hex, Hex),
	unix.SYS_MSGSND:                 makeSyscallInfo("msgsnd", Hex, Hex, Hex, Hex, Hex),
	unix.SYS_MSGRCV:                 makeSyscallInfo("msgrcv", Hex, Hex, Hex, Hex, Hex, Hex),
	unix.SYS_MSGCTL:                 makeSyscallInfo("msgctl", Hex, Hex, Hex, Hex),
	unix.SYS_FCNTL:                  makeSyscallInfo("fcntl", Hex, FD, Hex, Hex),
	unix.SYS_FLOCK:                  makeSyscallInfo("flock", Hex, FD, Hex),
	unix.SYS_FSYNC:                  makeSyscallInfo("fsync", Hex, FD),
	unix.SYS_FDATASYNC:              makeSyscallInfo("fdatasync", Hex, FD),
	unix.SYS_TRUNCATE:               makeSyscallInfo("truncate", Hex, Path, Hex),
	unix.SYS_FTRUNCATE:              makeSyscallInfo("ftruncate", Hex, FD, Hex),
	unix.SYS_GETDENTS:               makeSyscallInfo("getdents", Hex, Hex, Hex, Hex),
	unix.SYS_GETCWD:                 makeSyscallInfo("getcwd", Hex, PostPath, Hex),
	unix.SYS_CHDIR:                  makeSyscallInfo("chdir", Hex, Path),
	unix.SYS_FCHDIR:                 makeSyscallInfo("fchdir", Hex, Hex),
	unix.SYS_RENAME:                 makeSyscallInfo("rename", Hex, Path, Path),
	unix.SYS_MKDIR:                  makeSyscallInfo("mkdir", Hex, Path, Oct),
	unix.SYS_RMDIR:                  makeSyscallInfo("rmdir", Hex, Path),
	unix.SYS_CREAT:                  makeSyscallInfo("creat", FD, Path, Oct),
	unix.SYS_LINK:                   makeSyscallInfo("link", Hex, Path, Path),
	unix.SYS_UNLINK:                 makeSyscallInfo("unlink", Hex, Path),
	unix.SYS_SYMLINK:                makeSyscallInfo("symlink", Hex, Path, Path),
	unix.SYS_READLINK:               makeSyscallInfo("readlink", Hex, Path, ReadBuffer, Hex),
	unix.SYS_CHMOD:                  makeSyscallInfo("chmod", Hex, Path, Mode),
	unix.SYS_FCHMOD:                 makeSyscallInfo("fchmod", Hex, Hex, Mode),
	unix.SYS_CHOWN:                  makeSyscallInfo("chown", Hex, Path, Hex, Hex),
	unix.SYS_FCHOWN:                 makeSyscallInfo("fchown", Hex, Hex, Hex, Hex),
	unix.SYS_LCHOWN:                 makeSyscallInfo("lchown", Hex, Hex, Hex, Hex),
	unix.SYS_UMASK:                  makeSyscallInfo("umask", Hex, Hex),
	unix.SYS_GETTIMEOFDAY:           makeSyscallInfo("gettimeofday", Hex, Timeval, Hex),
	unix.SYS_GETRLIMIT:              makeSyscallInfo("getrlimit", Hex, Hex, Hex),
	unix.SYS_GETRUSAGE:              makeSyscallInfo("getrusage", Hex, Hex, Rusage),
	unix.SYS_SYSINFO:                makeSyscallInfo("sysinfo", Hex, Hex),
	unix.SYS_TIMES:                  makeSyscallInfo("times", Hex, Hex),
	unix.SYS_PTRACE:                 makeSyscallInfo("ptrace", Hex, PtraceRequest, PID, Hex, Hex),
	unix.SYS_GETUID:                 makeSyscallInfo("getuid", Hex),
	unix.SYS_SYSLOG:                 makeSyscallInfo("syslog", Hex, Hex, Hex, Hex),
	unix.SYS_GETGID:                 makeSyscallInfo("getgid", Hex),
	unix.SYS_SETUID:                 makeSyscallInfo("setuid", Hex, Hex),
	unix.SYS_SETGID:                 makeSyscallInfo("setgid", Hex, Hex),
	unix.SYS_GETEUID:                makeSyscallInfo("geteuid", Hex),
	unix.SYS_GETEGID:                makeSyscallInfo("getegid", Hex),
	unix.SYS_SETPGID:                makeSyscallInfo("setpgid", Hex, Hex, Hex),
	unix.SYS_GETPPID:                makeSyscallInfo("getppid", Hex),
	unix.SYS_GETPGRP:                makeSyscallInfo("getpgrp", Hex),
	unix.SYS_SETSID:                 makeSyscallInfo("setsid", Hex),
	unix.SYS_SETREUID:               makeSyscallInfo("setreuid", Hex, Hex, Hex),
	unix.SYS_SETREGID:               makeSyscallInfo("setregid", Hex, Hex, Hex),
	unix.SYS_GETGROUPS:              makeSyscallInfo("getgroups", Hex, Hex, Hex),
	unix.SYS_SETGROUPS:              makeSyscallInfo("setgroups", Hex, Hex, Hex),
	unix.SYS_SETRESUID:              makeSyscallInfo("setresuid", Hex, Hex, Hex, Hex),
	unix.SYS_GETRESUID:              makeSyscallInfo("getresuid", Hex, Hex, Hex, Hex),
	unix.SYS_SETRESGID:              makeSyscallInfo("setresgid", Hex, Hex, Hex, Hex),
	unix.SYS_GETRESGID:              makeSyscallInfo("getresgid", Hex, Hex, Hex, Hex),
	unix.SYS_GETPGID:                makeSyscallInfo("getpgid", Hex, Hex),
	unix.SYS_SETFSUID:               makeSyscallInfo("setfsuid", Hex, Hex),
	unix.SYS_SETFSGID:               makeSyscallInfo("setfsgid", Hex, Hex),
	unix.SYS_GETSID:                 makeSyscallInfo("getsid", Hex, Hex),
	unix.SYS_CAPGET:                 makeSyscallInfo("capget", Hex, Hex, Hex),
	unix.SYS_CAPSET:                 makeSyscallInfo("capset", Hex, Hex, Hex),
	unix.SYS_RT_SIGPENDING:          makeSyscallInfo("rt_sigpending", Hex, Hex),
	unix.SYS_RT_SIGTIMEDWAIT:        makeSyscallInfo("rt_sigtimedwait", Hex, Hex, Hex, Timespec, Hex),
	unix.SYS_RT_SIGQUEUEINFO:        makeSyscallInfo("rt_sigqueueinfo", Hex, Hex, Hex, Hex),
	unix.SYS_RT_SIGSUSPEND:          makeSyscallInfo("rt_sigsuspend", Hex, Hex),
	unix.SYS_SIGALTSTACK:            makeSyscallInfo("sigaltstack", Hex, StackT, StackT),
	unix.SYS_UTIME:                  makeSyscallInfo("utime", Hex, Path, Utimbuf),
	unix.SYS_MKNOD:                  makeSyscallInfo("mknod", Hex, Path, Mode, Hex),
	unix.SYS_USELIB:                 makeSyscallInfo("uselib", Hex, Hex),
	unix.SYS_PERSONALITY:            makeSyscallInfo("personality", Hex, Hex),
	unix.SYS_USTAT:                  makeSyscallInfo("ustat", Hex, Hex, Hex),
	unix.SYS_STATFS:                 makeSyscallInfo("statfs", Hex, Path, Hex),
	unix.SYS_FSTATFS:                makeSyscallInfo("fstatfs", Hex, Hex, Hex),
	unix.SYS_SYSFS:                  makeSyscallInfo("sysfs", Hex, Hex, Hex, Hex),
	unix.SYS_GETPRIORITY:            makeSyscallInfo("getpriority", Hex, Hex, Hex),
	unix.SYS_SETPRIORITY:            makeSyscallInfo("setpriority", Hex, Hex, Hex, Hex),
	unix.SYS_SCHED_SETPARAM:         makeSyscallInfo("sched_setparam", Hex, Hex, Hex),
	unix.SYS_SCHED_GETPARAM:         makeSyscallInfo("sched_getparam", Hex, Hex, Hex),
	unix.SYS_SCHED_SETSCHEDULER:     makeSyscallInfo("sched_setscheduler", Hex, Hex, Hex, Hex),
	unix.SYS_SCHED_GETSCHEDULER:     makeSyscallInfo("sched_getscheduler", Hex, Hex),
	unix.SYS_SCHED_GET_PRIORITY_MAX: makeSyscallInfo("sched_get_priority_max", Hex, Hex),
	unix.SYS_SCHED_GET_PRIORITY_MIN: makeSyscallInfo("sched_get_priority_min", Hex, Hex),
	unix.SYS_SCHED_RR_GET_INTERVAL:  makeSyscallInfo("sched_rr_get_interval", Hex, Hex, Hex),
	unix.SYS_MLOCK:                  makeSyscallInfo("mlock", Hex, Hex, Hex),
	unix.SYS_MUNLOCK:                makeSyscallInfo("munlock", Hex, Hex, Hex),
	unix.SYS_MLOCKALL:               makeSyscallInfo("mlockall", Hex, Hex),
	unix.SYS_MUNLOCKALL:             makeSyscallInfo("munlockall", Hex),
	unix.SYS_VHANGUP:                makeSyscallInfo("vhangup", Hex),
	unix.SYS_MODIFY_LDT:             makeSyscallInfo("modify_ldt", Hex, Hex, Hex, Hex),
	unix.SYS_PIVOT_ROOT:             makeSyscallInfo("pivot_root", Hex, Hex, Hex),
	unix.SYS__SYSCTL:                makeSyscallInfo("_sysctl", Hex, Hex),
	unix.SYS_PRCTL:                  makeSyscallInfo("prctl", Hex, Hex, Hex, Hex, Hex, Hex),
	unix.SYS_ARCH_PRCTL:             makeSyscallInfo("arch_prctl", Hex, ArchPrctl, Hex),
	unix.SYS_ADJTIMEX:               makeSyscallInfo("adjtimex", Hex, Hex),
	unix.SYS_SETRLIMIT:              makeSyscallInfo("setrlimit", Hex, Hex, Hex),
	unix.SYS_CHROOT:                 makeSyscallInfo("chroot", Hex, Path),
	unix.SYS_SYNC:                   makeSyscallInfo("sync", Hex),
	unix.SYS_ACCT:                   makeSyscallInfo("acct", Hex, Hex),
	unix.SYS_SETTIMEOFDAY:           makeSyscallInfo("settimeofday", Hex, Timeval, Hex),
	unix.SYS_MOUNT:                  makeSyscallInfo("mount", Hex, Path, Path, Path, Hex, Path),
	unix.SYS_UMOUNT2:                makeSyscallInfo("umount2", Hex, Path, Hex),
	unix.SYS_SWAPON:                 makeSyscallInfo("swapon", Hex, Hex, Hex),
	unix.SYS_SWAPOFF:                makeSyscallInfo("swapoff", Hex, Hex),
	unix.SYS_REBOOT:                 makeSyscallInfo("reboot", Hex, Hex, Hex, Hex, Hex),
	unix.SYS_SETHOSTNAME:            makeSyscallInfo("sethostname", Hex, Hex, Hex),
	unix.SYS_SETDOMAINNAME:          makeSyscallInfo("setdomainname", Hex, Hex, Hex),
	unix.SYS_IOPL:                   makeSyscallInfo("iopl", Hex, Hex),
	unix.SYS_IOPERM:                 makeSyscallInfo("ioperm", Hex, Hex, Hex, Hex),
	unix.SYS_CREATE_MODULE:          makeSyscallInfo("create_module", Hex, Path, Hex),
	unix.SYS_INIT_MODULE:            makeSyscallInfo("init_module", Hex, Hex, Hex, Hex),
	unix.SYS_DELETE_MODULE:          makeSyscallInfo("delete_module", Hex, Hex, Hex),
	unix.SYS_GET_KERNEL_SYMS:        makeSyscallInfo("get_kernel_syms", Hex, Hex),
	//	unix.SYS_QUERY_MODULE:query_module (only present in Linux < 2.6)
	unix.SYS_QUOTACTL:   makeSyscallInfo("quotactl", Hex, Hex, Hex, Hex, Hex),
	unix.SYS_NFSSERVCTL: makeSyscallInfo("nfsservctl", Hex, Hex, Hex, Hex),
	// 	unix.SYS_GETPMSG:getpmsg (not implemented in the Linux kernel)
	// 	unix.SYS_PUTPMSG:putpmsg (not implemented in the Linux kernel)
	// 	unix.SYSCALL:afs_syscall (not implemented in the Linux kernel)
	// 	unix.SYS_TUXCALL:tuxcall (not implemented in the Linux kernel)
	// 	unix.SYS_SECURITY:security (not implemented in the Linux kernel)
	unix.SYS_GETTID:            makeSyscallInfo("gettid", PID),
	unix.SYS_READAHEAD:         makeSyscallInfo("readahead", Hex, Hex, Hex, Hex),
	unix.SYS_SETXATTR:          makeSyscallInfo("setxattr", Hex, Path, Path, Hex, Hex, Hex),
	unix.SYS_LSETXATTR:         makeSyscallInfo("lsetxattr", Hex, Path, Path, Hex, Hex, Hex),
	unix.SYS_FSETXATTR:         makeSyscallInfo("fsetxattr", Hex, Hex, Path, Hex, Hex, Hex),
	unix.SYS_GETXATTR:          makeSyscallInfo("getxattr", Hex, Path, Path, Hex, Hex),
	unix.SYS_LGETXATTR:         makeSyscallInfo("lgetxattr", Hex, Path, Path, Hex, Hex),
	unix.SYS_FGETXATTR:         makeSyscallInfo("fgetxattr", Hex, Hex, Path, Hex, Hex),
	unix.SYS_LISTXATTR:         makeSyscallInfo("listxattr", Hex, Path, Path, Hex),
	unix.SYS_LLISTXATTR:        makeSyscallInfo("llistxattr", Hex, Path, Path, Hex),
	unix.SYS_FLISTXATTR:        makeSyscallInfo("flistxattr", Hex, Hex, Path, Hex),
	unix.SYS_REMOVEXATTR:       makeSyscallInfo("removexattr", Hex, Path, Path),
	unix.SYS_LREMOVEXATTR:      makeSyscallInfo("lremovexattr", Hex, Path, Path),
	unix.SYS_FREMOVEXATTR:      makeSyscallInfo("fremovexattr", Hex, Hex, Path),
	unix.SYS_TKILL:             makeSyscallInfo("tkill", Hex, PID, Signal),
	unix.SYS_TIME:              makeSyscallInfo("time", Hex, Hex),
	unix.SYS_FUTEX:             makeSyscallInfo("futex", Hex, Hex, FutexOp, Hex, Timespec, Hex, Hex),
	unix.SYS_SCHED_SETAFFINITY: makeSyscallInfo("sched_setaffinity", Hex, PID, Dec, CPUSet),
	unix.SYS_SCHED_GETAFFINITY: makeSyscallInfo("sched_getaffinity", Hex, PID, Dec, CPUSet),
	unix.SYS_SET_THREAD_AREA:   makeSyscallInfo("set_thread_area", Hex, Hex),
	unix.SYS_IO_SETUP:          makeSyscallInfo("io_setup", Hex, Hex, Hex),
	unix.SYS_IO_DESTROY:        makeSyscallInfo("io_destroy", Hex, Hex),
	unix.SYS_IO_GETEVENTS:      makeSyscallInfo("io_getevents", Hex, Hex, Hex, Hex, Hex, Timespec),
	unix.SYS_IO_SUBMIT:         makeSyscallInfo("io_submit", Hex, Hex, Hex, Hex),
	unix.SYS_IO_CANCEL:         makeSyscallInfo("io_cancel", Hex, Hex, Hex, Hex),
	unix.SYS_GET_THREAD_AREA:   makeSyscallInfo("get_thread_area", Hex, Hex),
	unix.SYS_LOOKUP_DCOOKIE:    makeSyscallInfo("lookup_dcookie", Hex, Hex, Hex, Hex),
	unix.SYS_EPOLL_CREATE:      makeSyscallInfo("epoll_create", FD, Hex),
	// 	unix.SYS_EPOLL_CTL_OLD:epoll_ctl_old (not implemented in the Linux kernel)
	// 	unix.SYS_EPOLL_WAIT_OLD:epoll_wait_old (not implemented in the Linux kernel)
	unix.SYS_REMAP_FILE_PAGES: makeSyscallInfo("remap_file_pages", Hex, Hex, Hex, Hex, Hex, Hex),
	unix.SYS_GETDENTS64:       makeSyscallInfo("getdents64", Hex, Hex, Hex, Hex),
	unix.SYS_SET_TID_ADDRESS:  makeSyscallInfo("set_tid_address", Hex, Hex),
	unix.SYS_RESTART_SYSCALL:  makeSyscallInfo("restart_syscall", Hex),
	unix.SYS_SEMTIMEDOP:       makeSyscallInfo("semtimedop", Hex, Hex, Hex, Hex, Hex),
	unix.SYS_FADVISE64:        makeSyscallInfo("fadvise64", Hex, Hex, Hex, Hex, Hex),
	unix.SYS_TIMER_CREATE:     makeSyscallInfo("timer_create", Hex, Hex, Hex, Hex),
	unix.SYS_TIMER_SETTIME:    makeSyscallInfo("timer_settime", Hex, Hex, Hex, ItimerSpec, PostItimerSpec),
	unix.SYS_TIMER_GETTIME:    makeSyscallInfo("timer_gettime", Hex, Hex, PostItimerSpec),
	unix.SYS_TIMER_GETOVERRUN: makeSyscallInfo("timer_getoverrun", Hex, Hex),
	unix.SYS_TIMER_DELETE:     makeSyscallInfo("timer_delete", Hex, Hex),
	unix.SYS_CLOCK_SETTIME:    makeSyscallInfo("clock_settime", Hex, Hex, Timespec),
	unix.SYS_CLOCK_GETTIME:    makeSyscallInfo("clock_gettime", Hex, Hex, PostTimespec),
	unix.SYS_CLOCK_GETRES:     makeSyscallInfo("clock_getres", Hex, Hex, PostTimespec),
	unix.SYS_CLOCK_NANOSLEEP:  makeSyscallInfo("clock_nanosleep", Hex, Hex, Hex, Timespec, PostTimespec),
	unix.SYS_EXIT_GROUP:       makeSyscallInfo("exit_group", Hex, Hex),
	unix.SYS_EPOLL_WAIT:       makeSyscallInfo("epoll_wait", Hex, FD, Hex, Hex, Hex),
	unix.SYS_EPOLL_CTL:        makeSyscallInfo("epoll_ctl", Hex, FD, Hex, FD, Hex),
	unix.SYS_TGKILL:           makeSyscallInfo("tgkill", Hex, PID, PID, Signal),
	unix.SYS_UTIMES:           makeSyscallInfo("utimes", Hex, Path, Timeval),
	// 	unix.SYS_VSERVER:vserver (not implemented in the Linux kernel)
	unix.SYS_MBIND:             makeSyscallInfo("mbind", Hex, Hex, Hex, Hex, Hex, Hex, Hex),
	unix.SYS_SET_MEMPOLICY:     makeSyscallInfo("set_mempolicy", Hex, Hex, Hex, Hex),
	unix.SYS_GET_MEMPOLICY:     makeSyscallInfo("get_mempolicy", Hex, Hex, Hex, Hex, Hex, Hex),
	unix.SYS_MQ_OPEN:           makeSyscallInfo("mq_open", Hex, Hex, Hex, Hex, Hex),
	unix.SYS_MQ_UNLINK:         makeSyscallInfo("mq_unlink", Hex, Hex),
	unix.SYS_MQ_TIMEDSEND:      makeSyscallInfo("mq_timedsend", Hex, Hex, Hex, Hex, Hex, Hex),
	unix.SYS_MQ_TIMEDRECEIVE:   makeSyscallInfo("mq_timedreceive", Hex, Hex, Hex, Hex, Hex, Hex),
	unix.SYS_MQ_NOTIFY:         makeSyscallInfo("mq_notify", Hex, Hex, Hex),
	unix.SYS_MQ_GETSETATTR:     makeSyscallInfo("mq_getsetattr", Hex, Hex, Hex, Hex),
	unix.SYS_KEXEC_LOAD:        makeSyscallInfo("kexec_load", Hex, Hex, Hex, Hex, Hex),
	unix.SYS_WAITID:            makeSyscallInfo("waitid", Hex, Hex, Hex, Hex, Hex, Rusage),
	unix.SYS_ADD_KEY:           makeSyscallInfo("add_key", Hex, Hex, Hex, Hex, Hex, Hex),
	unix.SYS_REQUEST_KEY:       makeSyscallInfo("request_key", Hex, Hex, Hex, Hex, Hex),
	unix.SYS_KEYCTL:            makeSyscallInfo("keyctl", Hex, Hex, Hex, Hex, Hex, Hex),
	unix.SYS_IOPRIO_SET:        makeSyscallInfo("ioprio_set", Hex, Hex, Hex, Hex),
	unix.SYS_IOPRIO_GET:        makeSyscallInfo("ioprio_get", Hex, Hex, Hex),
	unix.SYS_INOTIFY_INIT:      makeSyscallInfo("inotify_init", Hex),
	unix.SYS_INOTIFY_ADD_WATCH: makeSyscallInfo("inotify_add_watch", Hex, Hex, Hex, Hex),
	unix.SYS_INOTIFY_RM_WATCH:  makeSyscallInfo("inotify_rm_watch", Hex, Hex, Hex),
	unix.SYS_MIGRATE_PAGES:     makeSyscallInfo("migrate_pages", Hex, Hex, Hex, Hex, Hex),
	unix.SYS_OPENAT:            makeSyscallInfo("openat", FD, FD, Path, OpenFlags, Mode),
	unix.SYS_MKDIRAT:           makeSyscallInfo("mkdirat", Hex, FD, Path, Hex),
	unix.SYS_MKNODAT:           makeSyscallInfo("mknodat", Hex, FD, Path, Mode, Hex),
	unix.SYS_FCHOWNAT:          makeSyscallInfo("fchownat", Hex, FD, Path, Hex, Hex, Hex),
	unix.SYS_FUTIMESAT:         makeSyscallInfo("futimesat", Hex, FD, Path, Hex),
	unix.SYS_NEWFSTATAT:        makeSyscallInfo("newfstatat", Hex, Hex, Path, Stat, Hex),
	unix.SYS_UNLINKAT:          makeSyscallInfo("unlinkat", Hex, FD, Path, Hex),
	unix.SYS_RENAMEAT:          makeSyscallInfo("renameat", Hex, FD, Path, Hex, Path),
	unix.SYS_LINKAT:            makeSyscallInfo("linkat", Hex, Hex, Path, Hex, Path, Hex),
	unix.SYS_SYMLINKAT:         makeSyscallInfo("symlinkat", Hex, Path, Hex, Path),
	unix.SYS_READLINKAT:        makeSyscallInfo("readlinkat", Hex, Hex, Path, ReadBuffer, Hex),
	unix.SYS_FCHMODAT:          makeSyscallInfo("fchmodat", Hex, Hex, Path, Mode),
	unix.SYS_FACCESSAT:         makeSyscallInfo("faccessat", Hex, Hex, Path, Oct, Hex),
	unix.SYS_PSELECT6:          makeSyscallInfo("pselect6", Hex, FD, Hex, Hex, Hex, Hex, Hex),
	unix.SYS_PPOLL:             makeSyscallInfo("ppoll", Hex, Hex, Hex, Timespec, Hex, Hex),
	unix.SYS_UNSHARE:           makeSyscallInfo("unshare", Hex, Hex),
	unix.SYS_SET_ROBUST_LIST:   makeSyscallInfo("set_robust_list", Hex, Hex, Hex),
	unix.SYS_GET_ROBUST_LIST:   makeSyscallInfo("get_robust_list", Hex, Hex, Hex, Hex),
	unix.SYS_SPLICE:            makeSyscallInfo("splice", Hex, FD, Hex, FD, Hex, Hex, Hex),
	unix.SYS_TEE:               makeSyscallInfo("tee", Hex, FD, FD, Hex, Hex),
	unix.SYS_SYNC_FILE_RANGE:   makeSyscallInfo("sync_file_range", Hex, Hex, Hex, Hex, Hex),
	unix.SYS_VMSPLICE:          makeSyscallInfo("vmsplice", Hex, Hex, Hex, Hex, Hex),
	unix.SYS_MOVE_PAGES:        makeSyscallInfo("move_pages", Hex, Hex, Hex, Hex, Hex, Hex, Hex),
	unix.SYS_UTIMENSAT:         makeSyscallInfo("utimensat", Hex, Hex, Path, UTimeTimespec, Hex),
	unix.SYS_EPOLL_PWAIT:       makeSyscallInfo("epoll_pwait", Hex, FD, Hex, Hex, Hex, Hex, Hex),
	unix.SYS_EPOLL_PWAIT2:      makeSyscallInfo("epoll_pwait2", Hex, FD, Hex, Hex, Hex, Hex, Hex),
	unix.SYS_SIGNALFD:          makeSyscallInfo("signalfd", Hex, Hex, Hex, Hex),
	unix.SYS_TIMERFD_CREATE:    makeSyscallInfo("timerfd_create", Hex, Hex, Hex),
	unix.SYS_EVENTFD:           makeSyscallInfo("eventfd", Hex, Hex),
	unix.SYS_FALLOCATE:         makeSyscallInfo("fallocate", Hex, Hex, Hex, Hex, Hex),
	unix.SYS_TIMERFD_SETTIME:   makeSyscallInfo("timerfd_settime", Hex, Hex, Hex, ItimerSpec, PostItimerSpec),
	unix.SYS_TIMERFD_GETTIME:   makeSyscallInfo("timerfd_gettime", Hex, Hex, PostItimerSpec),
	unix.SYS_ACCEPT4:           makeSyscallInfo("accept4", Hex, Hex, PostSockAddr, SockLen, SockFlags),
	unix.SYS_SIGNALFD4:         makeSyscallInfo("signalfd4", Hex, Hex, Hex, Hex, Hex),
	unix.SYS_EVENTFD2:          makeSyscallInfo("eventfd2", Hex, Hex, Hex),
	unix.SYS_EPOLL_CREATE1:     makeSyscallInfo("epoll_create1", FD, Hex),
	unix.SYS_PIPE2:             makeSyscallInfo("pipe2", Hex, PipeFDs, Hex),
	unix.SYS_INOTIFY_INIT1:     makeSyscallInfo("inotify_init1", Hex, Hex),
	unix.SYS_PREADV:            makeSyscallInfo("preadv", Hex, Hex, ReadIOVec, Hex, Hex),
	unix.SYS_PWRITEV:           makeSyscallInfo("pwritev", Hex, Hex, WriteIOVec, Hex, Hex),
	unix.SYS_RT_TGSIGQUEUEINFO: makeSyscallInfo("rt_tgsigqueueinfo", Hex, Hex, Hex, Hex, Hex),
	unix.SYS_PERF_EVENT_OPEN:   makeSyscallInfo("perf_event_open", Hex, Hex, Hex, Hex, Hex, Hex),
	unix.SYS_RECVMMSG:          makeSyscallInfo("recvmmsg", Hex, Hex, Hex, Hex, Hex, Hex),
	unix.SYS_FANOTIFY_INIT:     makeSyscallInfo("fanotify_init", Hex, Hex, Hex),
	unix.SYS_FANOTIFY_MARK:     makeSyscallInfo("fanotify_mark", Hex, Hex, Hex, Hex, Hex, Hex),
	unix.SYS_PRLIMIT64:         makeSyscallInfo("prlimit64", Hex, Hex, Hex, Hex, Hex),
	unix.SYS_NAME_TO_HANDLE_AT: makeSyscallInfo("name_to_handle_at", Hex, Hex, Hex, Hex, Hex, Hex),
	unix.SYS_OPEN_BY_HANDLE_AT: makeSyscallInfo("open_by_handle_at", Hex, Hex, Hex, Hex),
	unix.SYS_CLOCK_ADJTIME:     makeSyscallInfo("clock_adjtime", Hex, Hex, Hex),
	unix.SYS_SYNCFS:            makeSyscallInfo("syncfs", Hex, Hex),
	unix.SYS_SENDMMSG:          makeSyscallInfo("sendmmsg", Hex, Hex, Hex, Hex, Hex),
	unix.SYS_SETNS:             makeSyscallInfo("setns", Hex, Hex, Hex),
	unix.SYS_GETCPU:            makeSyscallInfo("getcpu", Hex, Hex, Hex, Hex),
	unix.SYS_PROCESS_VM_READV:  makeSyscallInfo("process_vm_readv", Hex, Hex, ReadIOVec, Hex, IOVec, Hex, Hex),
	unix.SYS_PROCESS_VM_WRITEV: makeSyscallInfo("process_vm_writev", Hex, Hex, IOVec, Hex, WriteIOVec, Hex, Hex),
	unix.SYS_KCMP:              makeSyscallInfo("kcmp", Hex, Hex, Hex, Hex, Hex, Hex),
	unix.SYS_FINIT_MODULE:      makeSyscallInfo("finit_module", Hex, Hex, Hex, Hex),
	unix.SYS_SCHED_SETATTR:     makeSyscallInfo("sched_setattr", Hex, Hex, Hex, Hex),
	unix.SYS_SCHED_GETATTR:     makeSyscallInfo("sched_getattr", Hex, Hex, Hex, Hex),
	unix.SYS_RENAMEAT2:         makeSyscallInfo("renameat2", Hex, Hex, Path, Hex, Path, Hex),
	unix.SYS_SECCOMP:           makeSyscallInfo("seccomp", Hex, Hex, Hex, Hex),
}

// Signal table
var signals = [...]string{
	unix.SIGHUP:  "SIGHUP",    // hangup
	unix.SIGINT:  "SIGINT",    // interrupt
	unix.SIGQUIT: "SIGQUIT",   // quit
	unix.SIGILL:  "SIGILL",    // illegal instruction
	unix.SIGTRAP: "SIGTRAP",   // trace/breakpoint trap
	unix.SIGABRT: "SIGABRT",   // aborted
	unix.SIGBUS:  "SIGBUS",    // bus error
	unix.SIGFPE:  "SIGFPE",    // floating point exception
	unix.SIGKILL: "SIGKILL",   // killed
	unix.SIGUSR1: "SIGUSR1",   // user defined signal 1
	unix.SIGSEGV: "SIGSEGV",   // segmentation fault
	unix.SIGUSR2: "SIGUSR2",   // user defined signal 2
	unix.SIGPIPE: "SIGPIPE",   // broken pipe
	unix.SIGALRM: "SIGALRM",   // alarm clock
	unix.SIGTERM: "SIGTERM",   // terminated
	16:           "SIGSTKFLT", // stack fault
	17:           "SIGCHLD",   // child exited
	18:           "SIGCONT",   // continued
	19:           "SIGSTOP",   // stopped
	20:           "SIGTSTP",   // stopped
	21:           "SIGTTIN",   // stopped - tty input
	22:           "SIGTTOU",   // stopped - tty output
	23:           "SIGURG",    // urgent I/O condition
	24:           "SIGXCPU",   // CPU time limit exceeded
	25:           "SIGXFSZ",   // file size limit exceeded
	26:           "SIGVTALRM", // virtual timer expired
	27:           "SIGPROF",   // profiling timer expired
	28:           "SIGWINCH",  // window changed
	29:           "SIGPOLL",   // I/O possible
	30:           "SIGPWR",    // power failure
	31:           "SIGSYS",    // bad system call
}
